DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE authors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    age  INTEGER
);

CREATE TABLE books (
    isbn      VARCHAR(255) PRIMARY KEY,
    title     VARCHAR(255),
    author_id BIGINT,
    CONSTRAINT fk_books_author FOREIGN KEY (author_id) REFERENCES authors(id)
);
